version: '3'
services:
  database:
    image: mysql
    container_name: test-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
  toxiproxy:
    image: shopify/toxiproxy
    expose:
      - "22220"
